services:
  db:
    image: mariadb:10.6.4-focal
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_PASSWORD=nextpass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    expose:
      - 3306
      - 33060

  app:
    image: nextcloud
    restart: always
    container_name: nextcloud
    ports:
      - 80:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=nextpass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      
volumes:
  nextcloud:
  db:
